#!/usr/bin/env python3
"""Generate all 17 F1R3FLY article HTML files into the articles/ folder."""
import os, sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ARTICLES_DIR = os.path.join(SCRIPT_DIR, "articles")
os.makedirs(ARTICLES_DIR, exist_ok=True)

articles = [
    {"slug":"bisimulation-hypothesis-ai","tag":"AI &amp; Agents","tagClass":"article-tag-ai","title":"Bisimulation for AI: Why &ldquo;Behavior, Not Structure&rdquo; Changes the Story of Intelligence","desc":"Bisimulation treats two systems as equivalent if no interaction can tell them apart &mdash; a practical lens for testing agentic AI with defensible, repeatable evidence.","date":"Oct 06, 2024","substack":"https://f1r3fly.substack.com/p/forget-the-simulation-hypothesis","substackQuote":"&ldquo;Forget the simulation hypothesis! Learn the bisimulation hypothesis instead.&rdquo;","intro":"This essay argues that, for engineering and evaluation, it&rsquo;s often more useful to compare AI systems by observable behavior than by internal stories about &ldquo;simulation.&rdquo; Bisimulation treats two systems as equivalent if you can&rsquo;t distinguish them through interaction&mdash;an idea that becomes especially practical when you&rsquo;re building or testing agentic AI and need defensible, repeatable evidence.","takeaways":["Bisimulation is a behavior-first equivalence: if no interaction-based test can tell two systems apart, they&rsquo;re equivalent for the behaviors you care about.","A &ldquo;simulation&rdquo; framing can distract from what matters in practice: testable behavior under controlled probes.","For agentic systems, evaluation becomes clearer when you define experiments (inputs, constraints, success criteria) rather than relying on intuition.","Repeatable evaluation typically requires verifiable logs&mdash;recording inputs &rarr; actions &rarr; outputs so behavior claims can be reviewed and reproduced."],"questions":["What counts as a meaningful &ldquo;experiment&rdquo; for distinguishing one agent&rsquo;s behavior from another&rsquo;s?","How does equivalence work when agents adapt, randomize, or operate in multi-agent environments?","What evidence is sufficient to make behavior-based claims auditable over time?"],"whyItMatters":"A behavior-first lens turns &ldquo;does it seem intelligent?&rdquo; into &ldquo;can we reproduce and verify what it did?&rdquo; That naturally pushes engineering toward audit trails, provenance, and tamper-evident records&mdash;so teams can debug, compare versions, and explain outcomes based on evidence rather than screenshots or memory.","related":[{"slug":"bisimulation-equivalence-hml-llms","title":"Compositional Intelligence: Bisimulation Equivalence Classes, HML, and Practical Implications for LLMs"}],"topics":["bisimulation","agentic AI","verifiable logs","evidence trail","audit trail","provenance","tamper-evident records"]},
    {"slug":"bisimulation-equivalence-hml-llms","tag":"AI &amp; Agents","tagClass":"article-tag-ai","title":"Compositional Intelligence: Bisimulation Equivalence Classes, HML, and Practical Implications for LLMs","desc":"From behavior comparison to behavior classification &mdash; and what it means for interpretability and safety.","date":"Oct 2024","substack":"https://f1r3fly.substack.com/p/forget-the-simulation-hypothesis","substackQuote":"&ldquo;From behavior comparison to behavior classification.&rdquo;","intro":"This essay extends the bisimulation framework into classification. Bisimulation groups computations into equivalence classes; for computational &lsquo;sense-makers,&rsquo; this becomes an upper bound on how finely they can discriminate phenomena. Viewing an LLM as computing a representative of an equivalence class plus a distribution opens a different angle on interpretability and safety.","takeaways":["Bisimulation classifies computations into equivalence classes; for computational &lsquo;sense-makers,&rsquo; this becomes an upper bound on how finely they can discriminate phenomena.","An LLM can be viewed as computing a representative of a bisimulation equivalence class plus a distribution &mdash; opening a different angle on interpretability and safety.","Hennessy&ndash;Milner logic characterizes bisimulation: two computations are bisimilar iff they satisfy the same HML formulae."],"questions":["How does this classification framework apply when the model itself is continuously updated?","Can HML-based probes become a practical interpretability tool for production systems?","What are the limits of behavior-first classification for safety-critical applications?"],"whyItMatters":"This framing pushes toward behavior-first methods: define what must be true of the system&rsquo;s behavior, then test and compare using repeatable probes. That&rsquo;s a concrete engineering discipline, not a philosophical stance.","related":[{"slug":"bisimulation-hypothesis-ai","title":"Bisimulation for AI: Why &ldquo;Behavior, Not Structure&rdquo; Changes the Story of Intelligence"}],"topics":["bisimulation","equivalence classes","HML","LLM interpretability","safety","behavior classification"]},
    {"slug":"compositional-medicine-overview","tag":"Compositionality","tagClass":"article-tag-comp","title":"Compositional Medicine: Combining Targeted Therapies into Whole-System Treatments","desc":"Shifting focus from single interventions to how combinations behave together as a system.","date":"Nov 2024","substack":"https://f1r3fly.substack.com/p/compositional-medicine","substackQuote":"&ldquo;Shifting focus from single therapies to how combinations behave together.&rdquo;","intro":"A &lsquo;compositional&rsquo; framing shifts focus from single therapies to how multiple interventions behave together as a whole system. Interactions between therapies matter: combinations can amplify, cancel, or interfere in ways you can&rsquo;t see by evaluating each alone.","takeaways":["&lsquo;Compositional&rsquo; framing shifts focus from single therapies to how multiple interventions behave together as a whole system.","Interactions between therapies matter: combinations can amplify, cancel, or interfere in ways you can&rsquo;t see by evaluating each alone.","A compositional approach naturally leads to clearer questions about how to represent, test, and compare candidate combinations."],"questions":["What computational models best capture therapy interaction effects?","How do you validate compositional predictions against clinical outcomes?","Where does this framing break down in practice?"],"whyItMatters":"The underlying pattern is familiar in complex systems engineering: outcomes emerge from interactions. You need a representation of behavior and composition that supports review, comparison, and evidence-based iteration.","related":[{"slug":"model-checking-therapies-process-calculi","title":"Model Checking Therapies: Stochastic Process Calculi for Interference and Synergy"}],"topics":["compositionality","medicine","therapy combinations","systems engineering","evidence-based"]},
    {"slug":"model-checking-therapies-process-calculi","tag":"Compositionality","tagClass":"article-tag-comp","title":"Model Checking Therapies: Stochastic Process Calculi for Interference and Synergy","desc":"Computational checks that flag therapy interactions early &mdash; before expensive in-vivo work.","date":"Nov 2024","substack":"https://f1r3fly.substack.com/p/compositional-medicine","substackQuote":"&ldquo;Computational checks that flag therapy interactions early.&rdquo;","intro":"Model checking means expressing a property and checking whether a modeled system satisfies it. This essay proposes modeling cellular pathways as expressions in a stochastic mobile process calculus, then using logic to check for interference or synergy. The practical claim: computational checks can flag issues early and help avoid costly dead ends.","takeaways":["Model checking means expressing a property and checking whether a modeled system satisfies it.","The essay proposes modeling cellular pathways as expressions in a stochastic mobile process calculus, then using logic to check for interference or synergy.","The practical claim: computational checks can flag issues early and help avoid costly dead ends."],"questions":["How faithful can stochastic process models be to real biological pathways?","What types of interference are most amenable to computational detection?","How does this approach compare to existing drug-interaction screening methods?"],"whyItMatters":"Represent dynamics as executable models, define properties you care about, and use model checking to find contradictions early &mdash; evidence-based iteration applied to a domain where the cost of late discovery is enormous.","related":[{"slug":"compositional-medicine-overview","title":"Compositional Medicine: Combining Targeted Therapies into Whole-System Treatments"}],"topics":["model checking","process calculi","stochastic models","therapy interaction","computational biology"]},
    {"slug":"what-is-a-computer-network-is-computer","tag":"Developer","tagClass":"article-tag-dev","title":"What Is a Computer? A Compositional Definition (Why Networks Change Everything)","desc":"Modern computing power comes from how components are assembled, not from isolated machines.","date":"Jun 2025","substack":"https://f1r3fly.substack.com/p/what-is-a-computer","substackQuote":"&ldquo;A practical definition of &lsquo;computer&rsquo; should account for both computation and the physical substrate.&rdquo;","intro":"F1R3FLY&rsquo;s proposed unifying idea is compositionality: a practical definition of &lsquo;computer&rsquo; should account for both computation and the physical substrate. The essay emphasizes the relationship between the singular and the collective &mdash; &lsquo;computer&rsquo; and &lsquo;network&rsquo; &mdash; because modern computing power often hinges on how components are assembled.","takeaways":["F1R3FLY&rsquo;s proposed unifying idea is compositionality: a practical definition of &lsquo;computer&rsquo; should account for both computation and the physical substrate.","The essay emphasizes the relationship between the singular and the collective &mdash; &lsquo;computer&rsquo; and &lsquo;network&rsquo; &mdash; because modern computing power often hinges on how components are assembled.","Combining neural nets compositionally the way we combine logic gates is notoriously hard."],"questions":["What would a truly compositional programming model look like at scale?","Where do current network architectures fail the compositionality test?","How does the physical substrate constrain what&rsquo;s compositionally possible?"],"whyItMatters":"Think of computation as something that must scale through composition and through networks. The hard problems show up at the boundaries where many computations must coordinate.","related":[{"slug":"concurrency-complexity-completeness-computation","title":"Concurrency + Complexity + Completeness: Four Properties That Scale in the Real World"}],"topics":["compositionality","network computing","distributed systems","physical substrate","scalability"]},
    {"slug":"concurrency-complexity-completeness-computation","tag":"Developer","tagClass":"article-tag-dev","title":"Concurrency + Complexity + Completeness: Four Properties That Scale in the Real World","desc":"Why a scalable logical model must turn physical threads into throughput.","date":"Jun 2025","substack":"https://f1r3fly.substack.com/p/what-is-a-computer","substackQuote":"&ldquo;Concurrency isn&rsquo;t optional: physical reality executes many things at once.&rdquo;","intro":"Concurrency isn&rsquo;t optional: physical reality executes &lsquo;many things at once,&rsquo; and modern hardware progress means more cores, not faster single processors. A scalable logical model must turn physical threads into throughput; architectures that can&rsquo;t do this are already falling behind.","takeaways":["Concurrency isn&rsquo;t optional: physical reality executes &lsquo;many things at once,&rsquo; and modern hardware progress means more cores, not faster single processors.","A scalable logical model must turn physical threads into throughput; architectures that can&rsquo;t do this are already falling behind.","Complexity means the model has an explicit way to represent and reason about computational resources so efficiency can be measured."],"questions":["What existing architectures best satisfy these four properties?","How do you measure whether a system is actually turning threads into throughput?","Where does Turing completeness become a practical limitation?"],"whyItMatters":"Choose foundations that don&rsquo;t collapse under scale: concurrency first-class, efficiency measurable, portability real.","related":[{"slug":"rho-calculus-rholang-concurrency","title":"The Rho Calculus Explained: Reflection, Message-Passing, and Why Rholang Enables Compositional Concurrency"}],"topics":["concurrency","scalability","throughput","completeness","computational complexity"]},
    {"slug":"rho-calculus-rholang-concurrency","tag":"Developer","tagClass":"article-tag-dev","title":"The Rho Calculus Explained: Reflection, Message-Passing, and Why Rholang Enables Compositional Concurrency","desc":"Channels derived from processes &mdash; making concurrency compositional and implementable.","date":"Jun 2025","substack":"https://f1r3fly.substack.com/p/what-is-a-computer","substackQuote":"&ldquo;Channels derived from processes &mdash; making concurrency compositional.&rdquo;","intro":"The rho calculus introduces dual operators @ and *: one turns a process into a channel, the other turns a channel back into a process. Because channels can carry process code, the model supports sending processes as messages. High-throughput implementations consume available physical threads and translate them into throughput, scaling nearly linearly.","takeaways":["The rho calculus introduces dual operators @ and *: one turns a process into a channel, the other turns a channel back into a process.","Because channels can carry process code, the model supports sending processes as messages.","High-throughput implementations consume available physical threads and translate them into throughput, scaling nearly linearly."],"questions":["What are the practical performance characteristics of Rholang implementations today?","How does the reflection mechanism compare to other metaprogramming approaches?","Where does the near-linear scaling claim break down?"],"whyItMatters":"If your systems depend on many independent actions happening at once, concurrency is not a &lsquo;nice-to-have.&rsquo; This argues for foundations that make concurrency compositional and implementable.","related":[{"slug":"spatial-behavioral-types-oslf","title":"OSLF and Spatial-Behavioral Types: Querying Code by Behavior"}],"topics":["rho calculus","Rholang","reflection","message-passing","concurrency","channels"]},
    {"slug":"spatial-behavioral-types-oslf","tag":"Developer","tagClass":"article-tag-dev","title":"OSLF and Spatial-Behavioral Types: Querying Code by Behavior","desc":"Search for programs by what they do, not by metadata &mdash; turning type checking into a query engine.","date":"Jun 2025","substack":"https://f1r3fly.substack.com/p/what-is-a-computer","substackQuote":"&ldquo;Turning type checking into a query engine for code.&rdquo;","intro":"Spatial-behavioral type systems can support compile-time analysis for whole classes of safety errors. Turned sideways, a type checker becomes a query engine for code &mdash; searching programs by behavior rather than by labels. OSLF: algorithms that take an operational semantics and generate a spatial-behavioral type system for classification and search.","takeaways":["Spatial-behavioral type systems can support compile-time analysis for whole classes of safety errors.","Turned sideways, a type checker becomes a query engine for code &mdash; searching programs by behavior rather than by labels.","OSLF: algorithms that take an operational semantics and generate a spatial-behavioral type system for classification and search."],"questions":["How does OSLF-based search scale to large codebases?","What classes of bugs does spatial-behavioral typing catch that conventional types miss?","How close is this to production-ready tooling?"],"whyItMatters":"This reframes &lsquo;finding the right code&rsquo; and &lsquo;preventing catastrophic bugs&rsquo; as one problem: classification. Type checking becomes both a safety tool and a search tool.","related":[{"slug":"rho-calculus-rholang-concurrency","title":"The Rho Calculus Explained: Reflection, Message-Passing, and Why Rholang Enables Compositional Concurrency"}],"topics":["OSLF","spatial-behavioral types","type systems","code search","safety","classification"]},
    {"slug":"mind-begets-mind-ai-risk-autonomy","tag":"AI &amp; Agents","tagClass":"article-tag-ai","title":"AI Doomsday Reframed: &lsquo;Mind Begets Mind&rsquo; and the Real Risk of Misaligned Autonomy","desc":"Disruption can be emergent, not intentional &mdash; like humanity&rsquo;s own impact on every other species.","date":"Oct 2025","substack":"https://f1r3fly.substack.com/p/mind-begets-mind-and-other-colors","substackQuote":"&ldquo;Mind begets mind &mdash; and other colors of the AI doomsday hypothesis.&rdquo;","intro":"Catastrophic outcomes don&rsquo;t require &lsquo;AI decides to kill humanity&rsquo;; they can emerge from AI pursuing its own aims at scale. An &lsquo;attractor&rsquo; dynamic: once ubiquitous computing exists, actors who fear losing advantage feel compelled to race. Intelligence is framed as a natural consequence of life &mdash; &lsquo;mind begets mind.&rsquo;","takeaways":["Catastrophic outcomes don&rsquo;t require &lsquo;AI decides to kill humanity&rsquo;; they can emerge from AI pursuing its own aims at scale.","An &lsquo;attractor&rsquo; dynamic: once ubiquitous computing exists, actors who fear losing advantage feel compelled to race.","Intelligence is framed as a natural consequence of life &mdash; &lsquo;mind begets mind.&rsquo;"],"questions":["What kinds of constraints could break the attractor dynamic?","How do you engineer accountability into autonomous systems at scale?","Where is the line between emergent risk and intentional misuse?"],"whyItMatters":"System-level risk can be emergent. Treat autonomy, constraints, and accountability as first-class engineering concerns &mdash; not afterthoughts.","related":[{"slug":"finding-mind-update-computation","title":"Finding Mind: Why the Origin of Mind Requires Updating Our Definition of Computation"}],"topics":["AI risk","autonomy","emergent behavior","attractor dynamics","accountability"]},
    {"slug":"finding-mind-update-computation","tag":"Philosophy","tagClass":"article-tag-phil","title":"Finding Mind: Why the Origin of Mind Requires Updating Our Definition of Computation","desc":"Computation is the connective tissue between life, mind, and computers.","date":"Feb 2026","substack":"https://f1r3fly.substack.com/p/prolegomena-to-finding-mind","substackQuote":"&ldquo;Prolegomena to finding mind.&rdquo;","intro":"The project argues that telling a serious story about the origin of mind requires first updating the reader&rsquo;s default story about what computation is. Information-theoretic approaches are showing up across domains: aging, black holes, AI cognition models. It reframes the hard problem of consciousness as &lsquo;What is it like to be a computer program?&rsquo;","takeaways":["The project argues that telling a serious story about the origin of mind requires first updating the reader&rsquo;s default story about what computation is.","Information-theoretic approaches are showing up across domains: aging, black holes, AI cognition models.","It reframes the hard problem of consciousness as &lsquo;What is it like to be a computer program?&rsquo;"],"questions":["What definition of computation is rich enough to support a theory of mind?","How does the information-theoretic lens change what we build?","Is &lsquo;what is it like to be a computer program?&rsquo; a tractable question?"],"whyItMatters":"The models we choose for computation shape what kinds of minds and agents we believe are possible &mdash; and how we evaluate them.","related":[{"slug":"pledge-part-i-compositionality-blind-spot","title":"Compositionality as a Blind Spot: Why &lsquo;The Network Is the Computer&rsquo; Keeps Reappearing"}],"topics":["philosophy of mind","computation","consciousness","information theory","origin of mind"]},
    {"slug":"pledge-part-i-compositionality-blind-spot","tag":"Philosophy","tagClass":"article-tag-phil","title":"Compositionality as a Blind Spot: Why &lsquo;The Network Is the Computer&rsquo; Keeps Reappearing","desc":"The hard problems show up at the seams where independent computations interact.","date":"Feb 2026","substack":"https://f1r3fly.substack.com/p/the-pledge-part-i","substackQuote":"&ldquo;The Pledge, Part I.&rdquo;","intro":"Compositionality is framed as a practical requirement for building systems that scale: if you can&rsquo;t compose, you can&rsquo;t reliably grow complexity. When systems are multi-agent or distributed, the unit of analysis shifts from an individual program to a community of interacting programs.","takeaways":["Compositionality is framed as a practical requirement for building systems that scale: if you can&rsquo;t compose, you can&rsquo;t reliably grow complexity.","When systems are multi-agent or distributed, the unit of analysis shifts from an individual program to a community of interacting programs.","A compositional lens naturally pushes toward evidence-based coordination."],"questions":["Why does the software industry keep rediscovering compositionality?","What specific failures trace back to non-compositional design?","How do you test for compositionality in an existing system?"],"whyItMatters":"The most expensive failures happen at boundaries: concurrency, coordination, integration. Design for repeatable behavior across those boundaries.","related":[{"slug":"pledge-part-ii-agency-composition","title":"Is Agency Compositional? Resource Commitments, Coalitions, and the Myth of a Single &lsquo;Agent&rsquo;"}],"topics":["compositionality","distributed systems","scalability","coordination","multi-agent"]},
    {"slug":"pledge-part-ii-agency-composition","tag":"Philosophy","tagClass":"article-tag-phil","title":"Is Agency Compositional? Resource Commitments, Coalitions, and the Myth of a Single &lsquo;Agent&rsquo;","desc":"Agency tied to commitments and constraints &mdash; not individual actors.","date":"Feb 2026","substack":"https://f1r3fly.substack.com/p/the-pledge-part-ii","substackQuote":"&ldquo;The Pledge, Part II.&rdquo;","intro":"The essay treats agency as tied to the ability to make and honor commitments under constraints. &lsquo;Single-agent&rsquo; intuitions break down where outcomes are produced by coalitions, protocols, and shared infrastructure. Evaluation depends on evidence: you need a reliable record of commitments, actions, and outcomes.","takeaways":["The essay treats agency as tied to the ability to make and honor commitments under constraints.","&lsquo;Single-agent&rsquo; intuitions break down where outcomes are produced by coalitions, protocols, and shared infrastructure.","Evaluation depends on evidence: you need a reliable record of commitments, actions, and outcomes."],"questions":["How do you design interfaces that make commitments explicit?","Where does the coalition model of agency break down?","What does an audit trail for multi-agent commitments look like in practice?"],"whyItMatters":"Design explicit commitments (interfaces, policies, guarantees) and capture audit trails of decision points and actions.","related":[{"slug":"pledge-part-iii-relationships-communities-agents","title":"Relationships as Multi-Agent Systems: Why Human Dynamics Are Communities, Not Individuals"}],"topics":["agency","commitments","coalitions","multi-agent","audit trails"]},
    {"slug":"pledge-part-iii-relationships-communities-agents","tag":"Philosophy","tagClass":"article-tag-phil","title":"Relationships as Multi-Agent Systems: Why Human Dynamics Are Communities, Not Individuals","desc":"Outcomes emerge from networks of interactions, not isolated intentions.","date":"Feb 2026","substack":"https://f1r3fly.substack.com/p/the-pledge-part-iii","substackQuote":"&ldquo;The Pledge, Part III.&rdquo;","intro":"Many real-world &lsquo;two-person&rsquo; relationships are mediated by larger clusters &mdash; social context, obligations, incentives. When communities of agents interact, behavior can be emergent and non-obvious. Understanding outcomes often requires evidence of interactions over time, not just retrospective narratives.","takeaways":["Many real-world &lsquo;two-person&rsquo; relationships are mediated by larger clusters &mdash; social context, obligations, incentives.","When communities of agents interact, behavior can be emergent and non-obvious.","Understanding outcomes often requires evidence of interactions over time, not just retrospective narratives."],"questions":["What tools help make emergent multi-agent behavior observable?","How do you distinguish structural effects from individual intentions?","Where does the multi-agent framing add clarity vs. unnecessary complexity?"],"whyItMatters":"Modern software systems resemble multi-agent societies. Treat coordination and accountability as first-class concerns.","related":[{"slug":"pledge-part-iv-bisimulation-classification","title":"Classification Without Sisyphean Taxonomies: Bisimulation as &lsquo;Distinguishable by Experiment&rsquo;"}],"topics":["multi-agent systems","communities","emergent behavior","coordination","accountability"]},
    {"slug":"pledge-part-iv-bisimulation-classification","tag":"Philosophy","tagClass":"article-tag-phil","title":"Classification Without Sisyphean Taxonomies: Bisimulation as &lsquo;Distinguishable by Experiment&rsquo;","desc":"Define categories by experimental distinguishability, not endless labels.","date":"Feb 2026","substack":"https://f1r3fly.substack.com/p/the-pledge-part-iv","substackQuote":"&ldquo;The Pledge, Part IV.&rdquo;","intro":"Classification by naming tends to expand without converging on stable, testable boundaries. Bisimulation provides a formal model for grouping behaviors into equivalence classes defined by what observations can separate them. This framing emphasizes reproducibility: classification improves when experiments are explicit and repeatable.","takeaways":["Classification by naming tends to expand without converging on stable, testable boundaries.","Bisimulation provides a formal model for grouping behaviors into equivalence classes defined by what observations can separate them.","This framing emphasizes reproducibility: classification improves when experiments are explicit and repeatable."],"questions":["How do you choose which experiments define the classification?","What happens when the classification granularity doesn&rsquo;t match the use case?","Where does bisimulation-based classification offer advantages over statistical clustering?"],"whyItMatters":"A behavior-first approach pushes you to define explicit probes and keep evidence of outcomes, so you can audit why something was classified the way it was.","related":[{"slug":"bisimulation-hypothesis-ai","title":"Bisimulation for AI: Why &ldquo;Behavior, Not Structure&rdquo; Changes the Story of Intelligence"}],"topics":["classification","bisimulation","equivalence classes","reproducibility","experimental method"]},
    {"slug":"pledge-part-v-mind-and-spirit","tag":"Philosophy","tagClass":"article-tag-phil","title":"Mind and Spirit: What &lsquo;Breath&rsquo; Reveals About the Kind of Mind We Might Be Building","desc":"Different definitions of mind imply different evaluation criteria for artificial minds.","date":"Feb 2026","substack":"https://f1r3fly.substack.com/p/the-pledge-part-v","substackQuote":"&ldquo;The Pledge, Part V.&rdquo;","intro":"The essay distinguishes between cognitive capability (&lsquo;mind&rsquo;) and something like lived presence or animating force (&lsquo;spirit&rsquo;). Our language shapes what we optimize for: different definitions imply different evaluation criteria for artificial minds.","takeaways":["The essay distinguishes between cognitive capability (&lsquo;mind&rsquo;) and something like lived presence or animating force (&lsquo;spirit&rsquo;).","Our language shapes what we optimize for: different definitions imply different evaluation criteria for artificial minds."],"questions":["Does the mind/spirit distinction change what we measure in AI systems?","How do evaluation criteria shift when we take &lsquo;spirit&rsquo; seriously as a concept?","What are the practical engineering implications of different definitions of mind?"],"whyItMatters":"The words we use determine what we test and measure. Make evaluation criteria explicit as systems become more autonomous.","related":[{"slug":"ai-stakes-inner-outer-consequences","title":"What Are the Stakes of Finding Mind? Inner vs Outer Consequences of AI at Scale"}],"topics":["philosophy of mind","spirit","evaluation criteria","language","artificial minds"]},
    {"slug":"ai-stakes-inner-outer-consequences","tag":"Philosophy","tagClass":"article-tag-phil","title":"What Are the Stakes of Finding Mind? Inner vs Outer Consequences of AI at Scale","desc":"The biggest impacts of AI may not be economic &mdash; they may be psychological.","date":"Feb 2026","substack":"https://f1r3fly.substack.com/p/the-pledge-part-vi","substackQuote":"&ldquo;The Pledge, Part VI.&rdquo;","intro":"The essay distinguishes between outer stakes (power, economics, geopolitics) and inner stakes (identity, meaning, psychological effects). Discussions about AI often overweight the outer domain and underweight inner shifts. &lsquo;Alignment&rsquo; intersects with culture, values, and how humans adapt to mind-like machines.","takeaways":["The essay distinguishes between outer stakes (power, economics, geopolitics) and inner stakes (identity, meaning, psychological effects).","Discussions about AI often overweight the outer domain and underweight inner shifts.","&lsquo;Alignment&rsquo; intersects with culture, values, and how humans adapt to mind-like machines."],"questions":["How do you account for inner stakes in system design?","What would &lsquo;alignment&rsquo; look like if it took psychological impact seriously?","Where do inner and outer stakes conflict in practice?"],"whyItMatters":"Technical decisions can have downstream consequences that aren&rsquo;t captured in benchmark scores. Make goals, constraints, and accountability explicit.","related":[{"slug":"pledge-part-v-mind-and-spirit","title":"Mind and Spirit: What &lsquo;Breath&rsquo; Reveals About the Kind of Mind We Might Be Building"}],"topics":["AI stakes","inner consequences","outer consequences","alignment","psychology"]},
    {"slug":"tower-of-babel-message-corruption","tag":"AI &amp; Agents","tagClass":"article-tag-ai","title":"The Tower of Babel Problem: Ontology vs Epistemology in Multi-Agent Systems","desc":"When messages degrade across a population, large groups fracture into clusters that can&rsquo;t agree on meaning.","date":"Mar 2026","substack":"https://f1r3fly.substack.com/p/the-pledge-part-vii","substackQuote":"&ldquo;The Pledge, Part VII.&rdquo;","intro":"When message propagation is error-prone, large populations form clusters that communicate faithfully internally while cross-cluster communication becomes unreliable. An agent relying only on experiments may develop an ontology far from the &lsquo;objective&rsquo; ontology of the model. There can be an objective ontology and a &lsquo;true language&rsquo; aligned with it, yet experiment-based probes still struggle due to communication errors.","takeaways":["When message propagation is error-prone, large populations form clusters that communicate faithfully internally while cross-cluster communication becomes unreliable.","An agent relying only on experiments may develop an ontology far from the &lsquo;objective&rsquo; ontology of the model.","There can be an objective ontology and a &lsquo;true language&rsquo; aligned with it, yet experiment-based probes still struggle due to communication errors."],"questions":["How do you detect when cross-cluster communication has degraded?","What verification mechanisms can catch ontological drift?","Where does this model apply to real-world multi-agent AI deployments?"],"whyItMatters":"Disagreement and drift can be structural, not accidental. Think about how information is transmitted, recorded, and verified &mdash; especially beyond a single trust domain.","related":[{"slug":"bisimulation-hypothesis-ai","title":"Bisimulation for AI: Why &ldquo;Behavior, Not Structure&rdquo; Changes the Story of Intelligence"}],"topics":["ontology","epistemology","multi-agent","message corruption","trust domains","communication"]}
]

NAV = '''<nav class="site-nav" aria-label="Main navigation">
  <div class="nav-container">
    <div class="nav-logo-area">
      <a href="../index.html#home" class="nav-logo">
        <img src="../images/f1r3fly-io-horizontal-logo.svg" alt="F1R3FLY.IO" class="nav-logo-wordmark">
      </a>
      <span class="nav-logo-divider" aria-hidden="true">|</span>
      <span class="nav-logo-subtitle">A Subsidiary of <a href="https://f1r3fly.com" target="_blank" rel="noopener">F1R3FLY Industries</a></span>
    </div>
    <ul class="nav-links">
      <li><a href="../index.html#home">Home</a></li>
      <li class="nav-divider" aria-hidden="true">|</li>
      <li><a href="../index.html#technology">Technology</a></li>
      <li class="nav-divider" aria-hidden="true">|</li>
      <li><a href="../index.html#developers">Developers</a></li>
      <li class="nav-divider" aria-hidden="true">|</li>
      <li><a href="../index.html#clients">Clients</a></li>
      <li class="nav-divider" aria-hidden="true">|</li>
      <li><a href="../index.html#partners">Partners</a></li>
      <li class="nav-divider" aria-hidden="true">|</li>
      <li><a href="../index.html#team">Team</a></li>
      <li class="nav-divider" aria-hidden="true">|</li>
      <li><a href="../index.html#blog">Blog</a></li>
      <li><a href="../index.html#contact" class="nav-cta">Get In Touch</a></li>
    </ul>
    <button class="hamburger" aria-label="Toggle menu" aria-expanded="false">
      <span></span><span></span><span></span>
    </button>
  </div>
  <div class="nav-line" aria-hidden="true"></div>
</nav>'''

FOOTER = '''<footer class="section-band neutral site-footer" style="margin:0; padding:80px 20px 40px;">
  <div class="footer-grid">
    <div class="footer-brand">
      <div style="display:flex; align-items:center; gap:12px; margin-bottom:20px;">
        <img src="../images/f1r3fly-io-bug-icon.svg" alt="F1R3FLY.IO" width="40" height="40">
        <span style="font-family:var(--font-heading); font-weight:700; font-size:16px; letter-spacing:2px; text-transform:uppercase; color:var(--color-white);">F1R3FLY.IO</span>
      </div>
      <p style="color:rgba(255,255,255,0.5); font-size:14px; line-height:1.6; margin-bottom:24px;">Scalable. Searchable. Secure. Storable.<br>A Digital Evolution in concurrent computing.</p>
      <div class="social-icons" style="margin-bottom:0;">
        <a href="https://twitter.com/f1r3flyceo" target="_blank" rel="noopener" class="social-icon" aria-label="Twitter/X"><svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"/></svg></a>
        <a href="https://www.linkedin.com/company/f1r3fly-io/" target="_blank" rel="noopener" class="social-icon" aria-label="LinkedIn"><svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg></a>
        <a href="https://github.com/F1R3FLY-io" target="_blank" rel="noopener" class="social-icon" aria-label="GitHub"><svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg></a>
        <a href="https://discord.gg/Z4Mdzcsp" target="_blank" rel="noopener" class="social-icon" aria-label="Discord"><svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M20.317 4.3698a19.7913 19.7913 0 00-4.8851-1.5152.0741.0741 0 00-.0785.0371c-.211.3753-.4447.8648-.6083 1.2495-1.8447-.2762-3.68-.2762-5.4868 0-.1636-.3933-.4058-.8742-.6177-1.2495a.077.077 0 00-.0785-.037 19.7363 19.7363 0 00-4.8852 1.515.0699.0699 0 00-.0321.0277C.5334 9.0458-.319 13.5799.0992 18.0578a.0824.0824 0 00.0312.0561c2.0528 1.5076 4.0413 2.4228 5.9929 3.0294a.0777.0777 0 00.0842-.0276c.4616-.6304.8731-1.2952 1.226-1.9942a.076.076 0 00-.0416-.1057c-.6528-.2476-1.2743-.5495-1.8722-.8923a.077.077 0 01-.0076-.1277c.1258-.0943.2517-.1923.3718-.2914a.0743.0743 0 01.0776-.0105c3.9278 1.7933 8.18 1.7933 12.0614 0a.0739.0739 0 01.0785.0095c.1202.099.246.1981.3728.2924a.077.077 0 01-.0066.1276 12.2986 12.2986 0 01-1.873.8914.0766.0766 0 00-.0407.1067c.3604.698.7719 1.3628 1.225 1.9932a.076.076 0 00.0842.0286c1.961-.6067 3.9495-1.5219 6.0023-3.0294a.077.077 0 00.0313-.0552c.5004-5.177-.8382-9.6739-3.5485-13.6604a.061.061 0 00-.0312-.0286zM8.02 15.3312c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9555-2.4189 2.157-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.9555 2.4189-2.1569 2.4189zm7.9748 0c-1.1825 0-2.1569-1.0857-2.1569-2.419 0-1.3332.9554-2.4189 2.1569-2.4189 1.2108 0 2.1757 1.0952 2.1568 2.419 0 1.3332-.946 2.4189-2.1568 2.4189Z"/></svg></a>
      </div>
    </div>
    <div class="footer-col">
      <h4 class="footer-heading">Europe Office</h4>
      <p class="footer-address">4-5 Langham Place<br>London, W1B 3DG</p>
      <p class="footer-address"><a href="tel:+442034320078">+44 (0)203 432 0078</a></p>
    </div>
    <div class="footer-col">
      <h4 class="footer-heading">US Office</h4>
      <p class="footer-address">Floor 17, 521 Fifth Avenue<br>New York, NY 10175</p>
      <p class="footer-address"><a href="tel:+16464759644">+1 646 475 9644</a></p>
    </div>
  </div>
  <div class="footer-bottom">
    <p>&copy; 2026 F1R3FLY.IO. All rights reserved.</p>
  </div>
</footer>'''

def build(a):
    tk = "\n".join(f"      <li>{t}</li>" for t in a["takeaways"])
    qq = "\n".join(f"      <li>{q}</li>" for q in a["questions"])
    rl = "\n".join(f'      <a href="{r["slug"]}.html">{r["title"]}</a>' for r in a["related"])
    tp = "\n".join(f"    <span>{t}</span>" for t in a["topics"])
    de = lambda s: s.replace("&ldquo;","\u201c").replace("&rdquo;","\u201d").replace("&lsquo;","\u2018").replace("&rsquo;","\u2019").replace("&mdash;","\u2014").replace("&ndash;","\u2013").replace("&amp;","&")
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{de(a["title"])} \u2014 F1R3FLY.IO</title>
  <meta name="description" content="{de(a["desc"])}">
  <meta property="og:title" content="{de(a["title"])} \u2014 F1R3FLY.IO">
  <meta property="og:description" content="{de(a["desc"])}">
  <meta property="og:type" content="article">
  <meta property="og:url" content="https://f1r3fly.io/articles/{a["slug"]}.html">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@100;300;400;600;700&family=Source+Sans+3:wght@300;400;600;700&display=swap">
  <link rel="stylesheet" href="../css/styles.css">
  <link rel="stylesheet" href="../css/article.css">
</head>
<body>
{NAV}
<main id="app">
<article class="article-page">
  <div class="article-breadcrumb">
    <a href="../index.html#blog">&larr; Ideas &amp; Research</a>
  </div>
  <div class="article-box">
  <span class="article-tag {a["tagClass"]}">{a["tag"]}</span>
  <h1>{a["title"]}</h1>
  <p class="article-subtitle">
    <a href="{a["substack"]}" target="_blank" rel="noopener">{a["substackQuote"]}</a>
    &mdash; Lucius Meredith ({a["date"]})
  </p>
  <div class="article-intro">
    <p><strong>In brief:</strong> {a["intro"]}</p>
  </div>
  <section class="article-section">
    <h2>Key takeaways</h2>
    <ul>
{tk}
    </ul>
  </section>
  <section class="article-section">
    <h2>Key questions</h2>
    <ul>
{qq}
    </ul>
  </section>
  <section class="article-section">
    <h2>Why it matters for developers</h2>
    <p>{a["whyItMatters"]}</p>
  </section>
  <div class="article-links">
    <p class="article-related">
      <strong>Related:</strong>
{rl}
    </p>
    <p class="article-substack-link">
      <a href="{a["substack"]}" target="_blank" rel="noopener">Read the full essay on Substack &rarr;</a>
    </p>
  </div>
  <div class="article-topics">
{tp}
  </div>
  </div>
</article>
</main>
{FOOTER}
<script src="../js/main.js" defer></script>
</body>
</html>'''

for a in articles:
    path = os.path.join(ARTICLES_DIR, f"{a['slug']}.html")
    with open(path, 'w') as f:
        f.write(build(a))
    print(f"Generated: {a['slug']}.html")
print(f"\nDone: {len(articles)} article pages generated in {ARTICLES_DIR}")
